User.create!([
  { first_name: "Robert", last_name: "Smith", email: "robertsmith@gmail.com", password_digest: "$2a$12$wowsGKKf2mSM5oRe0xIlsOfnJ0dp4lL0j3dRiLkh1sIcOPUC1lxJq", image_url: "https://images.unsplash.com/photo-1597291970574-645f2fc92bc9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Sherri", last_name: "Homes", email: "sherrihomes@gmail.com", password_digest: "$2a$12$13PHzRP8mzUDeETnGi/MH.5cXdAbrjh/DhUwP2a3o/awa4moLpHH.", image_url: "https://images.unsplash.com/photo-1583318605147-8e52610d9c75?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Kristina", last_name: "Kendal", email: "kristinakendal@gmail.com", password_digest: "$2a$12$c2buYwo6Wzh0Jm2cIRScte3PPU/b/vRhyAAE0rrMx9hCifBFci/tS", image_url: "https://images.unsplash.com/photo-1599231666334-ca0dbd7ad2da?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Des", last_name: "Goodbert", email: "desgoodbert@gmail.com", password_digest: "$2a$12$45fI6qm4re7eEpY0q7GQmOPf1tF18vPBjPq/NrQ9qeV7pB6ZoK6uO", image_url: "https://images.unsplash.com/photo-1605270047806-a3dfe1448e54?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Hannah", last_name: "Scott", email: "hannahscott@gmail.com", password_digest: "$2a$12$Jy6t.du2C6qWHGENROBRPO103biAht8zD8zciUSSnW1SSLwYIS0DG", image_url: "https://images.unsplash.com/photo-1604858757869-29a18d0d9c5d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Tom", last_name: "Porter", email: "tomporter@gmail.com", password_digest: "$2a$12$.6P83Azv7DRefXAeTwhGAe57KudeEg6v4XtRsmnDFmXPRnOTjK2oe", image_url: "https://images.pexels.com/photos/3863793/pexels-photo-3863793.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { first_name: "Mike", last_name: "Smith", email: "mikesmith@gmail.com", password_digest: "$2a$12$ojRvArgUfNpNYyK20sv5Eur5xEYspQN3sT.Si9rWr7Q9sTYbuCghO", image_url: "https://images.unsplash.com/photo-1534351842133-0db61b907aac?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Shannon", last_name: "Larson", email: "shannonlarson@gmail.com", password_digest: "$2a$12$7YUVGt8fKbFfTgNTWG.mBeUMt2fc/12U8p/hw0v3gwvJfFXLn697m", image_url: "https://images.unsplash.com/photo-1602995596590-467a6357a9eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Chris", last_name: "Huggs", email: "chrishuggs@gmail.com", password_digest: "$2a$12$3ACqf73SYPJ5RelaBzHRH.umPwl2hyrN963TtO7a8.8Tb0X6175E.", image_url: "https://images.unsplash.com/photo-1604936725386-22a475291f50?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Lidia", last_name: "Parsons", email: "lidiaparsons@gmail.com", password_digest: "$2a$12$cepoH0BosyumFoMPe5k4z.IjDXdQQAnloZSrLm7QPS2CATKzwfEs6", image_url: "https://images.unsplash.com/photo-1602976871731-5ddd72ac13b2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Jennifer", last_name: "Degmoon", email: "jenniferdegmoon@gmail.com", password_digest: "$2a$12$uA.f6JAOyyH9Y.hlAyMbs.WOXpWS4ScaHd/3VmMiJMhaSmGi7bQSS", image_url: "https://images.unsplash.com/photo-1603723815349-2117d3a5394a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Serenity", last_name: "Marshall", email: "serentiymarshall@gmail.com", password_digest: "$2a$12$5L3o1ev06QPkVbuCiAbceOs/DDuxkbOTB0LxlCx.gJznKIyJ0EwZ.", image_url: "https://images.unsplash.com/photo-1584305556815-10ffcc71b179?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Mia", last_name: "Nester", email: "mianester@gmail.com", password_digest: "$2a$12$HSP9GMA2HzZMuAszU6ONT.pQ3uGIbJL5AKaDzAlqYpcgNpvvr97/a", image_url: "https://images.unsplash.com/photo-1573878221136-9b03f3d976b7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Rachel", last_name: "Renalds", email: "rachelrenalds@gmail.com", password_digest: "$2a$12$A22ZMj8s8gukTIkqZMknWOvbxza2etSCt8ZQj4wW4IKY43RTJMqpa", image_url: "https://images.unsplash.com/photo-1604247203891-ae01b7b2f1bb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Charlotte", last_name: "Webb", email: "charlottewebb@gmail.com", password_digest: "$2a$12$086Ho5VvgTpXlbhq/KoOG.EW34KLz/m.GvctBkqDv79rEfDunEpmG", image_url: "https://images.unsplash.com/photo-1604057242019-17b9f0843edf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Howie", last_name: "Hubert", email: "howiehubert@gmail.com", password_digest: "$2a$12$PJPnEQpswYQJp4EhabhxJOrIkTSF64alS1b6CX3i2WCZ6HWm/oA6q", image_url: "https://images.unsplash.com/photo-1603924498829-ce16c0da32aa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
])
Tag.create!([
  { name: "shade", image_url: "https://images.pexels.com/photos/4226171/pexels-photo-4226171.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "indirect light", image_url: "https://images.pexels.com/photos/5764081/pexels-photo-5764081.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "medium light", image_url: "https://images.pexels.com/photos/824572/pexels-photo-824572.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "full sun", image_url: "https://images.pexels.com/photos/788485/pexels-photo-788485.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "healthy roots", image_url: "https://images.pexels.com/photos/2421953/pexels-photo-2421953.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "no roots", image_url: "https://images.unsplash.com/photo-1592170577830-dece5e624fca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "normal humidity", image_url: "https://images.pexels.com/photos/4685959/pexels-photo-4685959.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "high humidity", image_url: "https://images.pexels.com/photos/4685958/pexels-photo-4685958.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "low humidity", image_url: "https://images.pexels.com/photos/1206591/pexels-photo-1206591.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "drought resistant", image_url: "https://images.pexels.com/photos/5103048/pexels-photo-5103048.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "easy care", image_url: "https://images.unsplash.com/photo-1593482892540-73c9199d8949?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "difficult care", image_url: "https://images.unsplash.com/photo-1602879952653-a3830f12a7cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "tropical", image_url: "https://images.unsplash.com/photo-1602229924961-ce7e191c375c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "foliage", image_url: "https://images.unsplash.com/photo-1511945362118-473ae753cba7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "common", image_url: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "rare", image_url: "https://images.unsplash.com/photo-1579830572457-0a18b87c2684?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "large", image_url: "https://images.unsplash.com/photo-1507746212228-2d3645cbeb56?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "small", image_url: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "seeds", image_url: "https://images.unsplash.com/photo-1508748169069-82590c9f26e6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "flowering", image_url: "https://images.unsplash.com/photo-1599598425947-5202edd56bdb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "cacti", image_url: "https://images.unsplash.com/photo-1554631221-f9603e6808be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "trailing/climbing", image_url: "https://images.unsplash.com/photo-1491941965945-eadfa7eede18?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "bulbs", image_url: "https://images.unsplash.com/photo-1512900606757-d64b6257bc35?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "succulents", image_url: "https://images.unsplash.com/photo-1484795945774-dcf93dc95861?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
])
Post.create!([
  { plant_type: "Pothos", trade_for: "Anything", description: "The picture is of the plant the clipping came from. It's been rooting for 2 weeks now.", location: "Manitou Springs, Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605652086/bh7jbbohqus7xtib71qh.jpg", user_id: 1 },
  { plant_type: "Calathea", trade_for: "Calathea", description: "I'd love to trade for a calathea I don't have. Let me know what you have! It'll just be a fresh clipping.", location: "Colorado Springs, CO", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605652404/xr1hekfudkd3cxyjirtd.jpg", user_id: 2 },
  { plant_type: "Monstera", trade_for: "Swiss Monstera", description: "I'll give a fresh clipping of my delicioso to anyone who has a swiss monstera they'd trade", location: "Castle Rock, CO", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605652782/kfbmnx5cdqvyi50emj10.jpg", user_id: 4 },
  { plant_type: "Wandering Dude", trade_for: "Anything", description: "I have an out of control wandering dude. Anyone want to trade?", location: "Colorado Springs, CO", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605652975/u1rqqe6cgzphdcqkt4k9.jpg", user_id: 5 },
  { plant_type: "Succulent", trade_for: "Succulent", description: "I honestly don't know what my succulents are named, but I'd be willing to trade some leaves for succulents I don't have.", location: "Colorado Springs, Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605653119/vqhcelcsskznhdfo8xsf.jpg", user_id: 6 },
  { plant_type: "Snake Plant", trade_for: "Anything", description: "I'm just looking for some new plants and I have a ton of snake plants.", location: "Manitou Springs, Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605653296/jkwfbeg8yygw97dhxric.jpg", user_id: 7 },
  { plant_type: "Pothos", trade_for: "Pothos", description: "I want new varieties of Pothos!", location: "Colorado Springs, CO", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605653464/pzvtkcivtkqkupocgo3h.jpg", user_id: 8 },
  { plant_type: "Purple Shamrock Bulbs", trade_for: "Gardening seeds", description: "I have bulbs I can trade if you have leftover gardening seeds", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605654421/tsismjcuoshbrfldt1zl.jpg", user_id: 9 },
  { plant_type: "Sensitive Plant Seeds", trade_for: "Garden seeds", description: "I have a ton of theses seeds and would like to trade them for any type of vegetable or fruit seed", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605669432/qxewj2l0p3ivmqgdbign.jpg", user_id: 3 },
  { plant_type: "philodendron", trade_for: "Philodendron", description: "I'm interested in trading different types of philodendron. Let me know what you have!", location: "Colorado Springs, CO", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605712396/nwyhfykmmshqcs0qisf7.jpg", user_id: 10 },
  { plant_type: "Silver Peperomia", trade_for: "Prince of Orange Philodendron", description: "I have this beautiful and healthy silver peperomia that I'd be willing to part with a limb to trade for a Prince of Orange!", location: "Manitou Springs", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605712766/yvhcqom4t2k2knvl37my.jpg", user_id: 11 },
  { plant_type: "Satin Pothos", trade_for: "Other rare pothos?", description: "This satin pothos is so crazy and out of control. I have it in a north facing window and it is looooooving life! Since I'll be trimming back soon, can I trade anyone for any other cool types of pothos? Maybe cool variegation?", location: "Colorado Springs", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605712988/ummjwydi2is8carqmfqk.jpg", user_id: 12 },
  { plant_type: "Arrowhead", trade_for: "Anything", description: "I just butchered my arrowhead into babies. Want one?", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605713127/ivibihszkjkauw38viik.jpg", user_id: 13 },
  { plant_type: "Maiden Hair Fern", trade_for: "Fern", description: "Want to share fern branches? Here's a baby fern branch unfurling for your enjoyment :)", location: "Manitou Springs", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605713267/jzvmwwdiy1nioxj47sal.jpg", user_id: 14 },
  { plant_type: "Monstera", trade_for: "Monstera", description: "I'm looking for a swiss monstera to trade with my delicioso", location: "Colorado Springs", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605714123/oxnzqlakfzdydqox5kgw.jpg", user_id: 14 },
  { plant_type: "Christmas Cactus", trade_for: "Cactus", description: "I have a rooted christmas cactus clipping. ", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605730427/lswtstc6du0tebjnyjzs.jpg", user_id: 15 },
  { plant_type: "Fern", trade_for: "Anything", description: "I don't really care what we trade for, but I have a fern I'm planning to split and would be willing to trade for something.", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605731032/p4trvnj30civ3zmwufsv.jpg", user_id: 1 },
  { plant_type: "Pothos", trade_for: "Pothos", description: "I have a lovely rooted clipping of my golden pothos. It's been rooting for a month now.", location: "Castle Rock", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605737172/k5rnozsugthwzthq5stm.jpg", user_id: 1 },
  { plant_type: "Cactus", trade_for: "Succulents", description: "I have a cactus I've had for a very long time and would love to trade for a succulent if anyone is intersted.", location: "Colorado Springs", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605795640/c8s4ntgsdfxheiszjjdf.jpg", user_id: 1 },
  { plant_type: "Umbrella Plant", trade_for: "Variegated Umbrella Plant", description: "I just want another type of umbrella plant. I'd give you a clipping from the one I have now to trade, but it won't be rooted.", location: "Manitou Springs, Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605796007/d0jwx1o3jjrx10byex5x.jpg", user_id: 1 },
  { plant_type: "Philodendron", trade_for: "Anything", description: "I'm not picky, but I've been itching for a new plant so I figured I'd trade instead of buying a new one. I can but you a few leaves to propagate when I decide who to trade with.", location: "Colorado Springs, Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605795851/rgrkxu23si51xncdjo68.jpg", user_id: 1 },
  { plant_type: "Princess Castle Cactus", trade_for: "Succulent", description: "I have a ton of little princess castle cacti. I'd love to trade for osme succulent leaves or a full succulent plant", location: "Colorado Springs, Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605799082/bslr0dnk0iii8tjyfpmd.jpg", user_id: 1 },
  { plant_type: "Prayer Plant", trade_for: "Anything", description: "I'd be willing to separate a few branches to trade for something I don't have. Let me know what you have to trade.", location: "Colorado Springs, Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605801299/zhxukscl1cczvp1cuusx.jpg", user_id: 1 },
])

PostTag.create!([
  { post_id: 1, tag_id: 2 },
  { post_id: 1, tag_id: 1 },
  { post_id: 1, tag_id: 5 },
  { post_id: 1, tag_id: 11 },
  { post_id: 1, tag_id: 15 },
  { post_id: 1, tag_id: 18 },
  { post_id: 1, tag_id: 22 },
  { post_id: 2, tag_id: 3 },
  { post_id: 2, tag_id: 6 },
  { post_id: 2, tag_id: 8 },
  { post_id: 2, tag_id: 12 },
  { post_id: 4, tag_id: 3 },
  { post_id: 4, tag_id: 6 },
  { post_id: 4, tag_id: 11 },
  { post_id: 4, tag_id: 14 },
  { post_id: 4, tag_id: 15 },
  { post_id: 5, tag_id: 2 },
  { post_id: 5, tag_id: 3 },
  { post_id: 5, tag_id: 11 },
  { post_id: 5, tag_id: 22 },
  { post_id: 6, tag_id: 4 },
  { post_id: 6, tag_id: 11 },
  { post_id: 6, tag_id: 10 },
  { post_id: 6, tag_id: 24 },
  { post_id: 7, tag_id: 3 },
  { post_id: 7, tag_id: 6 },
  { post_id: 7, tag_id: 10 },
  { post_id: 7, tag_id: 11 },
  { post_id: 8, tag_id: 1 },
  { post_id: 8, tag_id: 11 },
  { post_id: 8, tag_id: 15 },
  { post_id: 8, tag_id: 14 },
  { post_id: 9, tag_id: 23 },
  { post_id: 11, tag_id: 19 },
  { post_id: 12, tag_id: 2 },
  { post_id: 12, tag_id: 6 },
  { post_id: 12, tag_id: 11 },
  { post_id: 12, tag_id: 15 },
  { post_id: 13, tag_id: 2 },
  { post_id: 13, tag_id: 7 },
  { post_id: 13, tag_id: 16 },
  { post_id: 13, tag_id: 17 },
  { post_id: 14, tag_id: 2 },
  { post_id: 14, tag_id: 6 },
  { post_id: 14, tag_id: 7 },
  { post_id: 14, tag_id: 11 },
  { post_id: 14, tag_id: 22 },
  { post_id: 15, tag_id: 3 },
  { post_id: 15, tag_id: 15 },
  { post_id: 16, tag_id: 2 },
  { post_id: 16, tag_id: 15 },
  { post_id: 16, tag_id: 11 },
  { post_id: 10, tag_id: 3 },
  { post_id: 10, tag_id: 11 },
  { post_id: 10, tag_id: 15 },
])
Offer.create!([
  { post_id: 11, user_id: 9, message: "I have a ton of tomato seeds from last year. I'd love to trade!", image_url: nil, accepted: false },
  { post_id: 9, user_id: 9, message: "I've been looking for purple shamrock bulbs! I don't have any seeds, but I do have a rooted pothos clipping.", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605683708/kh7mospi7vjjnalmrdib.jpg", accepted: false },
  { post_id: 12, user_id: 9, message: "I'll trade for a leaf of one of my succulents!", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605731502/uqhtnvidquwcwk94ezpt.jpg", accepted: false },
  { post_id: 10, user_id: 1, message: "I'd love to take one! I can trade a clipping of my satin pothos.", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605737054/ptkdyxs6ugmwq5k56gg5.jpg", accepted: false },
  { post_id: 4, user_id: 9, message: "I would trade my lime pothos for it!", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605760444/djchefm8hl9frike37zm.jpg", accepted: true },
  { post_id: 12, user_id: 1, message: "I would love to trade for a swiss monstera. I added a picture of the plant you'd get a branch from. ", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605798911/w8vhhhbkwijxhbqgm4ma.jpg", accepted: false },
  { post_id: 9, user_id: 1, message: "I have a highly variegated golden pothos. I would love to trade for some of your satin pothos.", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605798954/y8padiwafaj0qkf2wuo6.jpg", accepted: false },
  { post_id: 5, user_id: 1, message: "Want to trade for a different type of wandering dude?", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605799333/taeusicebjes6drqart6.jpg", accepted: false },
  { post_id: 6, user_id: 1, message: "I have this succulent to trade if you don't already have it", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605799400/qewskvlf0pppnyygcboq.jpg", accepted: false },
  { post_id: 6, user_id: 1, message: "I want this plant", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605816656/tkitwsbhjsckwnw5xtha.jpg", accepted: false },
  { post_id: 8, user_id: 15, message: "Want a giant limb of my snake plant?", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605803640/fwqbtum2avvrch2rnyet.jpg", accepted: false },
  { post_id: 4, user_id: 2, message: "I have this airplant and I honestly don't even know if it's growing or not. I think someone else could take better care of it. Want to trade?", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605803688/nsfeql9abob598mxbalk.jpg", accepted: false },
  { post_id: 7, user_id: 3, message: "I'm wanting to split up my fern soon and would be willing to trade that for your prayer plant.", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605803732/uzncqsdf2fbfnw3m2aiu.jpg", accepted: false },
  { post_id: 2, user_id: 14, message: "I'd be willing to give up a branch of my swiss monstera", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605799674/yownl70fht8r2kjc3tbx.jpg", accepted: false },
  { post_id: 1, user_id: 3, message: "I want it", image_url: nil, accepted: false },
  { post_id: 2, user_id: 10, message: "I'll trade for a leaf of one of my succulents!", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605799484/v7mdofebcgznhfcclcju.jpg", accepted: false },
  { post_id: 6, user_id: 13, message: "I'd love to give you a Monstera leaf for this!", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605803975/upamsnrt8uefboty44tk.jpg", accepted: false },
])
