Tag.create!([
  { name: "shade", image_url: "https://images.pexels.com/photos/4226171/pexels-photo-4226171.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "indirect light", image_url: "https://images.pexels.com/photos/5764081/pexels-photo-5764081.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "medium light", image_url: "https://images.pexels.com/photos/824572/pexels-photo-824572.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "full sun", image_url: "https://images.pexels.com/photos/788485/pexels-photo-788485.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "healthy roots", image_url: "https://images.pexels.com/photos/2421953/pexels-photo-2421953.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "no roots", image_url: "https://images.unsplash.com/photo-1592170577830-dece5e624fca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "normal humidity", image_url: "https://images.pexels.com/photos/4685959/pexels-photo-4685959.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "high humidity", image_url: "https://images.pexels.com/photos/4685958/pexels-photo-4685958.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "low humidity", image_url: "https://images.pexels.com/photos/1206591/pexels-photo-1206591.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "drought resistant", image_url: "https://images.pexels.com/photos/5103048/pexels-photo-5103048.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { name: "easy care", image_url: "https://images.unsplash.com/photo-1593482892540-73c9199d8949?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "difficult care", image_url: "https://images.unsplash.com/photo-1602879952653-a3830f12a7cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "tropical", image_url: "https://images.unsplash.com/photo-1602229924961-ce7e191c375c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "foliage", image_url: "https://images.unsplash.com/photo-1511945362118-473ae753cba7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "common", image_url: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "rare", image_url: "https://images.unsplash.com/photo-1579830572457-0a18b87c2684?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "large", image_url: "https://images.unsplash.com/photo-1507746212228-2d3645cbeb56?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "small", image_url: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "seeds", image_url: "https://images.unsplash.com/photo-1508748169069-82590c9f26e6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "flowering", image_url: "https://images.unsplash.com/photo-1599598425947-5202edd56bdb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "cacti", image_url: "https://images.unsplash.com/photo-1554631221-f9603e6808be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "trailing/climbing", image_url: "https://images.unsplash.com/photo-1491941965945-eadfa7eede18?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "bulbs", image_url: "https://images.unsplash.com/photo-1512900606757-d64b6257bc35?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { name: "succulents", image_url: "https://images.unsplash.com/photo-1484795945774-dcf93dc95861?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
])
# Offer.create!([
#   { post_id: 49, user_id: 2, message: "Nevermind I don't want this anymore", image_url: nil, accepted: true },
#   { post_id: 49, user_id: 24, message: "I would love to have this!", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605405715/e8rf4wpyox8r55ttepdx.jpg", accepted: false },
#   { post_id: 57, user_id: 1, message: "I want it", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605124097/hymmev4n2f5b53wxpq5e.jpg", accepted: true },
#   { post_id: 39, user_id: 24, message: "I want it", image_url: nil, accepted: false },
#   { post_id: 1, user_id: 3, message: "I'd love to take this clipping!", image_url: nil, accepted: nil },
#   { post_id: 1, user_id: 2, message: "I'd love to take it! I can trade for this guy.", image_url: "https://images.unsplash.com/photo-1592170577830-dece5e624fca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80", accepted: nil },
#   { post_id: 1, user_id: 2, message: "hello hi pick me!!!!!!", image_url: nil, accepted: nil },
#   { post_id: 9, user_id: 2, message: "I'd love to trade", image_url: nil, accepted: nil },
#   { post_id: 31, user_id: 1, message: "Gimme that", image_url: nil, accepted: false },
#   { post_id: 31, user_id: 1, message: "Gimme that", image_url: nil, accepted: false },
#   { post_id: 1, user_id: 1, message: "I'd love to trade!", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605038982/k4udby7exazpwek2xxyv.jpg", accepted: nil },
#   { post_id: 58, user_id: 2, message: "I want this", image_url: nil, accepted: false },
#   { post_id: 58, user_id: 2, message: "I'll take it", image_url: nil, accepted: false },
#   { post_id: 1, user_id: 2, message: "I'll trade for a christmas cactus!", image_url: "https://images.unsplash.com/photo-1543591359-7bc08a61c4cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1187&q=80", accepted: false },
#   { post_id: 7, user_id: 1, message: "Gimme that plant", image_url: nil, accepted: false },
#   { post_id: 39, user_id: 1, message: "Gimme this plant", image_url: nil, accepted: false },
#   { post_id: 4, user_id: 2, message: "I want this!!", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605050252/j7utnr2alktq5mzel05n.jpg", accepted: false },
#   { post_id: 50, user_id: 1, message: "Pick me!", image_url: nil, accepted: false },
#   { post_id: 47, user_id: 24, message: "I want this!", image_url: nil, accepted: false },
#   { post_id: 58, user_id: 2, message: "I want this", image_url: nil, accepted: false },
# ])
# Post.create!([
#   { plant_type: "Satin Pothos", trade_for: "Any other pothos", description: "Beautiful, shimmery, healthy pothos", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1604788928/ohhbjcvu9ytms8gem6c6.jpg", user_id: 2 },
#   { plant_type: "Christmas Cactus", trade_for: "Any", description: "cactus", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1604789045/ovcockswzh91ys4x0tvl.jpg", user_id: 2 },
#   { plant_type: "Monstera", trade_for: "Anything", description: "Rooted branch", location: "Colorado Springs CO", image_url: nil, user_id: 1 },
#   { plant_type: "Snake Plant", trade_for: "Spider Plant", description: "Healthy, rooted snake plant", location: "Colorado Springs", image_url: nil, user_id: 3 },
#   { plant_type: "Ivy", trade_for: "Anything", description: "Just clipped this ivy vine. Anyone want it?", location: "Colorado Springs", image_url: nil, user_id: 6 },
#   { plant_type: "Neon Pothos", trade_for: "Anything", description: "Clipped these a month ago. Very healthy roots", location: "Colorado Springs", image_url: nil, user_id: 7 },
#   { plant_type: "Spider Plant", trade_for: "Pothos", description: "I cut off the babies. Any takers? I'd love a pothos to trade.", location: "Colorado Springs", image_url: nil, user_id: 8 },
#   { plant_type: "Aloe", trade_for: "Anything", description: "My daughter knocked off a huge leg of my aloe. Would love to trade it for something", location: "Colorado Springs", image_url: nil, user_id: 9 },
#   { plant_type: "Christmas Cactus", trade_for: "Christmas Cactus", description: "I have a huge christmas cactus and would love to trade a fresh clipping for a different type. Mind has red flowers", location: "Colorado Springs", image_url: nil, user_id: 10 },
#   { plant_type: "Zebra Plant", trade_for: "Cactus", description: "Zebra Plant", location: "Colorado Springs", image_url: nil, user_id: 11 },
#   { plant_type: "Philodendron", trade_for: "Anything", description: "I've been propogating this guy for a week now.", location: "Colorado Springs", image_url: nil, user_id: 11 },
#   { plant_type: "Common Ivy", trade_for: "ZZ Plant", description: "I've been searching for a Raven ZZ Plant. Anyone want some common ivy for it?", location: "Colorado Springs", image_url: nil, user_id: 13 },
#   { plant_type: "Elephant Bush", trade_for: "Anything", description: "I'd be willing for propogate for a good trade offer. Maybe a cactus of some kind?", location: "Colorado Springs", image_url: nil, user_id: 14 },
#   { plant_type: "Golden Pothos", trade_for: "Fern", description: "The propogated vine looks a little sickly. Anyone still want it?", location: "Colorado Springs", image_url: nil, user_id: 6 },
#   { plant_type: "Wandering Dude", trade_for: "Anything", description: "Trying to trim my wandering dude and want the clippings to go to a good home.", location: "Colorado Springs", image_url: nil, user_id: 17 },
#   { plant_type: "Monstera", trade_for: "Swiss Monstera", description: "Really want a Swiss Monstera to trade. I'd be willing to cut a branch off my giant monstera", location: "Colorado Springs", image_url: nil, user_id: 18 },
#   { plant_type: "Peacelily", trade_for: "Aloe", description: "Just trying to get rid of my peacelily", location: "Colorado Springs", image_url: nil, user_id: 9 },
#   { plant_type: "Nerve Plant", trade_for: "Anything", description: "Nerve Plant", location: "Colorado Springs", image_url: nil, user_id: 20 },
#   { plant_type: "Ivy", trade_for: "Monstera", description: "Rooted branch", location: "Colorado Springs CO", image_url: nil, user_id: 1 },
#   { plant_type: "Neon Pothos", trade_for: "Golden Pothos", description: "Healthy clipping I've been rooting for 1 month. Ready to plant.", location: "Colorado Springs, CO", image_url: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80", user_id: 1 },
#   { plant_type: "Common Ivy", trade_for: "Any", description: "Good shape", location: "Colorado", image_url: "https://images.unsplash.com/photo-1491941965945-eadfa7eede18?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1052&q=80", user_id: 2 },
#   { plant_type: "Umbrella Treeee", trade_for: "Anything", description: "Beautiful variegated umbrella tree clipping", location: "Colorado Springs CO", image_url: nil, user_id: 1 },
#   { plant_type: "Parlor Palm!!!", trade_for: "Nothing", description: "I just watn to get rid of it", location: "colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1604788452/b2up9iwixijl0jibd4bq.jpg", user_id: 24 },
#   { plant_type: "Common Ivy", trade_for: "Nothing", description: "It's good", location: "colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1604788550/a5bqenod101by4sqr0rz.jpg", user_id: 2 },
#   { plant_type: "Pothos", trade_for: "Monstera", description: "Good roots", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1604788605/p9ivpxsfpsgxj35rqhby.jpg", user_id: 2 },
#   { plant_type: "Hen and Chick Cactus", trade_for: "Any", description: "hi", location: "Colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1604788655/oqracumnuqxeyhjg7q0d.jpg", user_id: 2 },
#   { plant_type: "Umbrella Tree", trade_for: "Nothing", description: "Beautiful variegated umbrella tree clipping", location: "Colorado Springs CO", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1604788739/xqnjxi9z6cd1kqkgaydy.jpg", user_id: 2 },
#   { plant_type: "cactus", trade_for: "nothing", description: "it's a good plant", location: "colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1604692734/cuca7gar74obwycwhisx.jpg", user_id: 1 },
#   { plant_type: "Peperomia", trade_for: "Cactus", description: "It's a great clipping", location: "colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605033747/my3vjiejwr9jcjqqfrhg.jpg", user_id: 1 },
#   { plant_type: "Monstera", trade_for: "Pothos", description: "Healthy, rooted in water", location: "colorado", image_url: "https://res.cloudinary.com/djka3ehcg/image/upload/v1605124065/amb1l5q76zj4cz6tnmcs.jpg", user_id: 1 },
#   { plant_type: "Pothos", trade_for: "Anything", description: "good, rooted clipping", location: "colorado", image_url: nil, user_id: 2 },
# ])
# PostTag.create!([
#   { post_id: 49, tag_id: 6 },
#   { post_id: 49, tag_id: 7 },
#   { post_id: 49, tag_id: 10 },
#   { post_id: 49, tag_id: 14 },
#   { post_id: 47, tag_id: 8 },
#   { post_id: 47, tag_id: 11 },
#   { post_id: 4, tag_id: 7 },
#   { post_id: 9, tag_id: 1 },
#   { post_id: 9, tag_id: 2 },
#   { post_id: 9, tag_id: 3 },
#   { post_id: 9, tag_id: 4 },
#   { post_id: 9, tag_id: 26 },
#   { post_id: 4, tag_id: 8 },
#   { post_id: 4, tag_id: 11 },
#   { post_id: 4, tag_id: 13 },
#   { post_id: 50, tag_id: 20 },
#   { post_id: 10, tag_id: 2 },
#   { post_id: 10, tag_id: 19 },
#   { post_id: 10, tag_id: 13 },
#   { post_id: 11, tag_id: 16 },
#   { post_id: 11, tag_id: 23 },
#   { post_id: 11, tag_id: 24 },
#   { post_id: 12, tag_id: 4 },
#   { post_id: 12, tag_id: 20 },
#   { post_id: 12, tag_id: 23 },
#   { post_id: 13, tag_id: 3 },
#   { post_id: 13, tag_id: 27 },
#   { post_id: 13, tag_id: 4 },
#   { post_id: 13, tag_id: 2 },
#   { post_id: 14, tag_id: 5 },
#   { post_id: 14, tag_id: 6 },
#   { post_id: 14, tag_id: 30 },
#   { post_id: 14, tag_id: 4 },
#   { post_id: 15, tag_id: 6 },
#   { post_id: 15, tag_id: 32 },
#   { post_id: 15, tag_id: 26 },
#   { post_id: 15, tag_id: 2 },
#   { post_id: 17, tag_id: 37 },
#   { post_id: 18, tag_id: 23 },
#   { post_id: 18, tag_id: 16 },
#   { post_id: 19, tag_id: 6 },
#   { post_id: 50, tag_id: 26 },
#   { post_id: 36, tag_id: 6 },
#   { post_id: 56, tag_id: 7 },
#   { post_id: 1, tag_id: 20 },
#   { post_id: 1, tag_id: 23 },
#   { post_id: 56, tag_id: 19 },
#   { post_id: 57, tag_id: 1 },
#   { post_id: 57, tag_id: 26 },
#   { post_id: 58, tag_id: 24 },
#   { post_id: 58, tag_id: 26 },
#   { post_id: 39, tag_id: 1 },
#   { post_id: 39, tag_id: 7 },
#   { post_id: 39, tag_id: 8 },
#   { post_id: 39, tag_id: 11 },
# ])
User.create!([
  { first_name: "Karl", last_name: "Kandy", email: "karlkandy@gmail.com", password_digest: "$2a$12$PJPnEQpswYQJp4EhabhxJOrIkTSF64alS1b6CX3i2WCZ6HWm/oA6q", image_url: "https://images.unsplash.com/photo-1603924498829-ce16c0da32aa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Robert", last_name: "Smith", email: "robertsmith@gmail.com", password_digest: "$2a$12$wowsGKKf2mSM5oRe0xIlsOfnJ0dp4lL0j3dRiLkh1sIcOPUC1lxJq", image_url: "https://images.unsplash.com/photo-1597291970574-645f2fc92bc9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Sherri", last_name: "Homes", email: "sherrihomes@gmail.com", password_digest: "$2a$12$13PHzRP8mzUDeETnGi/MH.5cXdAbrjh/DhUwP2a3o/awa4moLpHH.", image_url: "https://images.unsplash.com/photo-1583318605147-8e52610d9c75?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Kristina", last_name: "Kendal", email: "kristinakendal@gmail.com", password_digest: "$2a$12$c2buYwo6Wzh0Jm2cIRScte3PPU/b/vRhyAAE0rrMx9hCifBFci/tS", image_url: "https://images.unsplash.com/photo-1599231666334-ca0dbd7ad2da?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Des", last_name: "Goodbert", email: "desgoodbert@gmail.com", password_digest: "$2a$12$45fI6qm4re7eEpY0q7GQmOPf1tF18vPBjPq/NrQ9qeV7pB6ZoK6uO", image_url: "https://images.unsplash.com/photo-1605270047806-a3dfe1448e54?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Hannah", last_name: "Scott", email: "hannahscott@gmail.com", password_digest: "$2a$12$Jy6t.du2C6qWHGENROBRPO103biAht8zD8zciUSSnW1SSLwYIS0DG", image_url: "https://images.unsplash.com/photo-1604858757869-29a18d0d9c5d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Tom", last_name: "Porter", email: "tomporter@gmail.com", password_digest: "$2a$12$.6P83Azv7DRefXAeTwhGAe57KudeEg6v4XtRsmnDFmXPRnOTjK2oe", image_url: "https://images.pexels.com/photos/3863793/pexels-photo-3863793.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
  { first_name: "Mike", last_name: "Smith", email: "mikesmith@gmail.com", password_digest: "$2a$12$ojRvArgUfNpNYyK20sv5Eur5xEYspQN3sT.Si9rWr7Q9sTYbuCghO", image_url: "https://images.unsplash.com/photo-1534351842133-0db61b907aac?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Shannon", last_name: "Larson", email: "shannonlarson@gmail.com", password_digest: "$2a$12$7YUVGt8fKbFfTgNTWG.mBeUMt2fc/12U8p/hw0v3gwvJfFXLn697m", image_url: "https://images.unsplash.com/photo-1602995596590-467a6357a9eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Chris", last_name: "Huggs", email: "chrishuggs@gmail.com", password_digest: "$2a$12$3ACqf73SYPJ5RelaBzHRH.umPwl2hyrN963TtO7a8.8Tb0X6175E.", image_url: "https://images.unsplash.com/photo-1604936725386-22a475291f50?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Lidia", last_name: "Parsons", email: "lidiaparsons@gmail.com", password_digest: "$2a$12$cepoH0BosyumFoMPe5k4z.IjDXdQQAnloZSrLm7QPS2CATKzwfEs6", image_url: "https://images.unsplash.com/photo-1602976871731-5ddd72ac13b2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Jennifer", last_name: "Degmoon", email: "jenniferdegmoon@gmail.com", password_digest: "$2a$12$uA.f6JAOyyH9Y.hlAyMbs.WOXpWS4ScaHd/3VmMiJMhaSmGi7bQSS", image_url: "https://images.unsplash.com/photo-1603723815349-2117d3a5394a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Serenity", last_name: "Marshall", email: "serentiymarshall@gmail.com", password_digest: "$2a$12$5L3o1ev06QPkVbuCiAbceOs/DDuxkbOTB0LxlCx.gJznKIyJ0EwZ.", image_url: "https://images.unsplash.com/photo-1584305556815-10ffcc71b179?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Mia", last_name: "Nester", email: "mianester@gmail.com", password_digest: "$2a$12$HSP9GMA2HzZMuAszU6ONT.pQ3uGIbJL5AKaDzAlqYpcgNpvvr97/a", image_url: "https://images.unsplash.com/photo-1573878221136-9b03f3d976b7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Rachel", last_name: "Renalds", email: "rachelrenalds@gmail.com", password_digest: "$2a$12$A22ZMj8s8gukTIkqZMknWOvbxza2etSCt8ZQj4wW4IKY43RTJMqpa", image_url: "https://images.unsplash.com/photo-1604247203891-ae01b7b2f1bb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Ben", last_name: "Jamin", email: "benjamin@gmail.com", password_digest: "$2a$12$Q81KVNmR9sDqkTBq4dcrT.MKTXi8sPY4IMDsx8c36Zrgm5/9VjGEq", image_url: "https://images.unsplash.com/photo-1585928502031-c9dc266230ec?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Howie", last_name: "Hubertt", email: "howiehubert@gmail.com", password_digest: "$2a$12$1GF7zXzLCRf0.AXpRvJ7Kefzdy91nJ7wCCTRkySgxZ8b29tN5on8C", image_url: "https://images.unsplash.com/photo-1530983822321-fcac2d3c0f06?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Gabby", last_name: "Stoom", email: "gabbystoom@gmail.com", password_digest: "$2a$12$4CS2xt6Yi7tRBqaE4cD/nOAm8FfjU4FM.Xz4ZLiVy1ZajLhjPPNOS", image_url: "https://images.unsplash.com/photo-1575633660442-9d3526b47a70?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Charlotte", last_name: "Webb", email: "charlottewebb@gmail.com", password_digest: "$2a$12$086Ho5VvgTpXlbhq/KoOG.EW34KLz/m.GvctBkqDv79rEfDunEpmG", image_url: "https://images.unsplash.com/photo-1604057242019-17b9f0843edf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" },
  { first_name: "Betty", last_name: "Klein", email: "bettyklein@gmail.com", password_digest: "$2a$12$e80.i5jBXmlsdSXx7hnRT.thlAd8U/2DyYX/zQgeFypUTK4twBn7m", image_url: "https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" },
])
